### ISSUE TITLE
Notice: Undefined index: c

### ISSUE THREAD

**Issue by OllieCrook** [phpMv/ubiquity-devtools#1]
`Notice: Undefined index: c in /Users/ollie/Ubiquity/blog/vendor/phpmv/ubiquity/src/Ubiquity/controllers/Startup.php on line 32`

**Steps taken:**
1. `curl -s http://getcomposer.org/installer | php`
2. `composer global require phpmv/ubiquity-devtools`
3. `Ubiquity new blog`
4. `cd blog`
5. `php -S 127.0.0.1:8090`
6. `http://127.0.0.1:8090`

**Tried:**
1. Updating Composer
2. Using PHP 7.3 + 7.2

**Comment by jcheron** [comment]
Hello,
Ubiquity Startup use a `c` parameter in Url.
So with php as server, you must provide this parameter with a router file.
Create this `.htrouter.php` file in the base root of your web application:

```php
$uri = ltrim(urldecode(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH)),'/');
if (!file_exists(__DIR__ . '/' .$uri)) {
	$_GET['c'] = $uri;
}else{
	$_GET['c']='';
}
return false;
```

And then you can call in console:
```
php -S 127.0.0.1:8090 .htrouter.php
```

**Comment by jcheron** [comment]
It will be necessary to modify the **siteUrl** key in the configuration file `app/config/config.php`:
```php
	"siteUrl"=>"http://127.0.0.1:8090/",
```

**Comment by jcheron** [comment]
Devtools now have a ``serve`` command to start a development server and avoid this type of inconvenience
Run from the root of your application:
```bash
Ubiquity serve
```

see https://github.com/phpMv/ubiquity-devtools/releases/tag/v1.1.3
