### ISSUE TITLE
Question pb on project creation

### ISSUE THREAD

**Issue by jcheron** [phpMv/ubiquity-devtools#16]
When creating a project:
```
Ubiquity new test-project
```

>Do you want to run composer install ? (y/n)

Unable to enter the answer to the question in the console.

**Comment by jcheron** [comment]
@gildonei 
For the STDIN problem, I'd have to be able to reproduce it.
What is your version of Windows?
Did you already have this problem in PHP 7.3?

see https://github.com/phpMv/ubiquity/issues/56#issuecomment-579886169

**Comment by gildonei** [comment]
I'm using Win10 full updated
Using WAMP 3.2.2.2 with php 7.4 in console and 7.4 in apache

I made a pr in ubiquity-devtools with a fix that worked to me.

**Comment by jcheron** [comment]
This is a php 7.4.0 issue, on Windows: see https://bugs.php.net/bug.php?id=78883
The problem is solved in 7.4.1.

Windows snapshots containing the fix for this bug are available at
https://windows.php.net/downloads/snaps/php-7.4/r996f217
