### ISSUE TITLE
Ubiquity command not found

### ISSUE THREAD

**Issue by gildonei** [phpMv/ubiquity-devtools#2]
I tried to install devtools on Win10 (full updated) but after installation, Ubiquity command was not found. I have default composer installation, setted on Windows Path and Ubiquity was not found.

![ubiquity-not-found](https://user-images.githubusercontent.com/1370979/54378279-bc853b00-4665-11e9-87bf-9c6839112c75.png)

Composer.bat file is installed at C:\ProgramData\ComposerSetup\bin and devtools was installed at C:\Users\Gildonei\AppData\Roaming\Composer\vendor

Should I try to move /bin and /phpmv folders to composer installation path?

**Comment by gildonei** [comment]
To make ubiquity work I had to manually set ubiquity devtools in system path variable C:\Users\Gildonei\AppData\Roaming\Composer\vendor\bin

**Comment by jcheron** [comment]
Yes, it would be the same for all global installations with Composer ...
The `bin` folder of `Composer` is never in the default path, whatever the os used.

I think it should be added in the doc.

**Comment by gildonei** [comment]
I did a PR with a tip to setup Ubiquity bin dir to Path if it doesn't work by default

**Comment by jcheron** [comment]
Thanks!
Given the importance of this message, you could put it in an important admonition.

```
.. important:: Your message
```

**Comment by gildonei** [comment]
Done! Add **.. important::** before added comment
