### ISSUE TITLE
Error running 'help' after first install

### ISSUE THREAD

**Issue by andrei-dascalu** [phpMv/ubiquity-devtools#21]
Hello,

I'm trying to use devtools to setup my first ubiquity project, but I ran into the following issue:

`composer global require phpmv/ubiquity-devtools`

it runs ok and installs `phpmv/ubiquity-devtools (1.2.16)` and `phpmv/ubiquity-commands (0.0.10)`. After this I do

`Ubiquity help project`

and the result is

```bash
· Message : Class 'Ubiquity\utils\base\UIntrospection' not found                                               │
     │      · File : <home>/.composer/vendor/phpmv/ubiquity-commands/src/Ubiquity/devtools/cmd/Command.php        │
     │      · Line :  562
```

Is there a dependency missing?

On the other hand `Ubiquity version` executes and provides

```bash
    · PHP 7.4.10
    · Ubiquity devtools (1.2.16)
```

Thanks

**Comment by jcheron** [comment]
Thanks @andrei-dascalu !
it is indeed a bug, which appears only if you are not in the project folder.
It will be solved in the next **Ubiquity-commands** release.

**Comment by jcheron** [comment]
see https://github.com/phpMv/ubiquity-commands/releases/tag/0.0.11

**Comment by andrei-dascalu** [comment]
@jcheron thanks! I was trying to use the devtools to create the project (rather than use compose) so basically I wanted devtools installed globally standalone before I had a project.

**Comment by jcheron** [comment]
yes, devtools are also made for that.
